/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package santander.coders.rebels.ic;

import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        IC ic = new IC();

        System.out.println("Bem-vindo à Inteligência Central dos Rebeldes!");
        System.out.println("Insira as inforações dos aspirantes a novos Rebeldes.");

        boolean wantAddNewAspirant = true;
        while (wantAddNewAspirant) {
            System.out.println("Informe o nome: ");
            String name = scanner.nextLine();

            System.out.println("Informe a idade: ");
            int age = scanner.nextInt();

            int raceKind;
            do {
                System.out.println("Informe a raça: ");
                for (RaceKind item : RaceKind.values()) {
                    System.out.printf("%d - %s%n", item.ordinal(), item);
                }
                raceKind = scanner.nextInt();
            } while (raceKind < 0 || raceKind >= RaceKind.values().length);

            Rebel rebel = new Rebel(name, age, RaceKind.values()[raceKind]);

            ic.addRebel(rebel);

            System.out.println("Insira S para informar mais um aspirante. Insira qualquer outra letra para encerrar.");
            char addNewAspirant = scanner.next().charAt(0);
            scanner.nextLine();

            wantAddNewAspirant = addNewAspirant == 'S' || addNewAspirant == 's';
        }

        try {
            ic.printRebels();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

    }
}
